config/routes.rb
Rails.application.routes.draw do


  devise_for :users

  authenticated :user do

    resources :comments
    resources :skills
    resources :workers
    resources :documents

    resources :clients

    resources :tasks do
      post :set_status, on: :member
      post :set_worker, on: :member
      get :documents, on: :member
    end

    resources :languages
    resources :access_rights, only: [:index, :update, :destroy]

    get '/match', to: 'home#match'
    post '/match/results', to: 'home#match_results'
  end

  root 'home#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :to_lang, class_name: :Language
  belongs_to :from_lang, class_name: :Language
  belongs_to :client
  belongs_to :worker
  has_many :documents
  has_many :comments

  scope :sorted, -> {order :id}
  scope :active, -> {where status: [:new, :assigned, :working, :finished, :ready, :rejected]}
  scope :unassigned, -> {where status: :new}
  scope :assigned, -> {where status: :assigned}
  scope :working, -> {where status: :working}
  scope :finished, -> {where status: :finished}
  scope :ready, -> {where status: :ready}
  scope :rejected, -> {where status: :rejected}
  scope :closed, -> {where status: :closed}

  ALLOWED_STATUSES = [:new, :assigned, :working, :finished, :ready, :rejected, :canceled, :closed]

  validates_presence_of :to_lang, :from_lang, :deadline, :price, :quality, :size
  validates_numericality_of :price, greater_than: 0
  validates_numericality_of :quality,
                            only_integer: true,
                            less_than_or_equal_to: 10,
                            greater_than_or_equal_to: 1
  validates_numericality_of :size,
                            only_integer: true,
                            greater_than: 0
  validate :languages_are_different

  before_save :check_status

  after_create :send_project_manager_message_on_create
  after_save :send_assigned_message
  after_save :send_finished_message
  after_save :send_rejected_message
  after_save :send_client_message_on_ready

  def check_status
    if status.to_sym == :new && worker
      self.status = :assigned
    end
    if status.to_sym == :assigned && !worker
      self.status = :new
    end
  end

  def languages_are_different
    if to_lang.id == from_lang.id
      errors.add :from_lang, ''
      errors.add :to_lang, ''
    end
  end

  def send_project_manager_message_on_create
    ClientMailer.new_to_projectmanager(self).deliver_now
  end

  def send_assigned_message
    ClientMailer.assigned_to_translator(self).deliver_now if status_changed? && status.to_sym == :assigned
  end

  def send_finished_message
    ClientMailer.finished_to_profreader(self).deliver_now if status_changed? && status.to_sym == :finished
  end

  def send_rejected_message
    ClientMailer.rejected_to_translator(self).deliver_now if status_changed? && status.to_sym == :rejected
  end

  def send_client_message_on_ready
    if status_changed? && status.to_sym == :ready
      ClientMailer.ready(self).deliver_now
      ClientMailer.ready_to_clientmanager(self).deliver_now
    end
  end
end

app/controllers/tasks_controller.rb
require 'zip'

class TasksController < ApplicationController
  before_action :control_access_read
  before_action :control_access_edit, only: [:new, :edit, :create, :update]
  before_action :control_access_delete, only: [:destroy]


  before_action :set_task, only: [:show, :edit, :update, :destroy, :documents]
  before_action :set_tasks, only: [:index]

  # GET /tasks
  # GET /tasks.json
  def index
    if params[:q]
      redirect_to url_for(params.except(:filter)) if params[:filter]
      @special_tasks = []
      if params[:q] == params[:q].to_i.to_s
        @tasks = Task.where(id: params[:q])
      else
        @tasks = Task.where('LOWER(description) LIKE ?', "%#{params[:q].mb_chars.downcase}%")
      end
    elsif params[:filter]
      @special_tasks = []
      @tasks = Task.where(status: params[:filter].keys)
    elsif current_user.client_manager? || current_user.profreader? || current_user.admin? || current_user.project_manager?
      if params[:client_id]
        @tasks = Task.where(client_id: params[:client_id])
        @tasks = @tasks.page params[:page]
      else
        @tasks = Task.all
      end

      @special_tasks = []
      @special_tasks = @tasks.where(status: :ready) if current_user.client_manager?
      @special_tasks = @tasks.where(status: :finished) if current_user.profreader?
      @special_tasks = @tasks.where(status: :new) if current_user.project_manager?

      if @special_tasks.any?
        ids = @tasks.pluck(:id) - @special_tasks.pluck(:id)
        @tasks = Task.where(id: ids)
      end
    else
      @special_tasks = []
      @tasks = Task.where(status: [:assigned, :working, :finished, :rejected], worker_id: current_user.worker.id) if current_user.translator?
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
    if [:new, :assigned].include?(@task.status.to_sym) && (current_user.admin? || current_user.project_manager?)
      @workers = Worker.all
      if params[:q]
        @workers = @workers.where("LOWER(name) LIKE ?", "%#{params[:q].mb_chars.downcase}%")
      end
      @workers = @workers.to_a.select {|x| x.accepts?(@task).result }
      @workers = [@task.worker] + Worker.where(id: @workers.map(&:id) - [@task.worker_id]) if @task.worker
    end
  end

  def set_status
    Task.find(params[:id]).update! set_status_params
    puts edit_task_url(id: params[:id]), '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
    redirect_to edit_task_url id: params[:id]
  end

  def set_worker
    @task = Task.find(params[:id])
    if params[:worker_id]
      @task.update! worker_id: Worker.find(params[:worker_id]).id
    else
      @task.update! worker_id: nil
    end
    redirect_to :back
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to edit_task_url(@task) }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to edit_task_url(@task)}
     else
        format.html { render :edit }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end


  def documents
    file = Tempfile.new('files.zip')

    names = []

    Zip::File.open(file.path, Zip::File::CREATE) do |zipfile|
      @task.documents.where(kind: params[:kind]).each do |document|
        name = document.name
        if names.include? name
          i = 1
          while names.include? name
            splitted = document.name.split '.'
            if splitted.count == 1
              name = document.name + '-' + i.to_s
            else
              splitted[splitted.count - 2] =  splitted[splitted.count - 2]  + '-' + i.to_s
              name = splitted.join '.'
            end
            i = i + 1
          end
        end
        names << name
        zipfile.add(name, document.document.path)
      end
    end

    send_data File.read(file.path), filename: 'document.zip'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  def set_tasks
    if params[:finished]
      @tasks = Task.where(finished: params[:finished]).sorted
    else
      @tasks = Task.all.sorted
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def task_params
    params.require(:task).permit(:to_lang_id, :from_lang_id, :deadline, :price, :quality, :size, :finished, :description, :status, :client_id)
  end

  def set_status_params
    params.require(:task).permit(:finished)
  end

  def control_access_read
    redirect_to root_path unless current_user.admin? ||
                                 current_user.profreader? ||
                                 current_user.client_manager? ||
                                 current_user.translator? ||
                                 current_user.project_manager?
  end

  def control_access_edit
    true
  end

  def control_access_delete
    redirect_to root_path unless current_user.admin?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper

def date_format(date)

end

end

app/views/tasks/_form.html.slim
.row
  .small-12.columns
    - client_id = params[:client_id] || @task.client_id
    - client_id = nil if client_id == 'new'
    - unless client_id
      h3 Добавьте клиента
      - if @task.new_record?
        = render 'clients/form', client: Client.new, source: :new_task
      - else
        = render 'clients/form', client: Client.new, source: :task, task_id: @task.id
      h3 или выберите существующего
      .small-12.columns.search-row
        = form_tag(clients_path, method: :get, remote: true, format: :json) do
          .row.collapse
            - unless @task.new_record?
              input type='hidden' name='task_id' value=@task.id
            .small-4.columns
              = link_to 'Все', :clients, class: 'button prefix'
            .small-6.columns
              = text_field_tag :q, params[:q], placeholder: 'Поиск'
            .small-2.columns
              input type='submit' class="button postfix" value='Поиск'
      table#clients_list

    - else
      - statuses_to_set = []
      - if current_user.admin?
        - statuses_to_set = ['new', 'working', 'finished', 'ready', 'rejected', 'canceled', 'closed'] - @task.status.to_s
      - if current_user.translator?
        - statuses_to_set << 'working' if ['assigned', 'rejected'].include? @task.status.to_s
        - statuses_to_set << 'finished' if ['working'].include? @task.status.to_s
      - if current_user.profreader? && @task.status.to_s == 'finished'
        - statuses_to_set += ['ready', 'rejected']
      - if current_user.client_manager?
        - statuses_to_set << 'canceled' unless ['closed', 'canceled'].include? @task.status.to_s
        - statuses_to_set += ['closed', 'rejected'] if @task.status.to_s == 'ready'
      - if !@task.new_record? && statuses_to_set.any?
        h3 Установить статус
        .row
          - statuses_to_set.each do |status|
            .small-2.columns
              = form_for(@task, html: {'data-abide'=> true}) do |f|
                = f.hidden_field :status, value: status
                = f.submit t('status.' + status), class: 'button expand'
      - if [:new, :assigned, :rejected].include?(@task.status.to_sym) && (current_user.admin? || current_user.project_manager?)
        h3 Назначить исполнителя
        .row
          .small-12.columns
            .search-row
              = form_tag(edit_task_path(@task), method: :get) do
                .row.collapse
                  .small-10.columns
                    = text_field_tag :q, params[:q], placeholder: 'Поиск'
                  .small-2.columns
                    input type='submit' class="button postfix" value=t('search')
        .row
          .small-12.columns
            - if @workers.count > 0
              table
                tbody
                  thead
                    tr
                      th Имя
                      th = t '.price'
                      th Языки
                      th Текущие заказы
                tbody
                  - @workers.each do |worker|
                    tr class=('current' if @task.worker_id == worker.id)
                      - if @task.worker_id == worker.id
                        td
                          = worker.name
                          | &nbsp;
                          = link_to set_worker_task_path(@task, worker_id: nil), method: :post
                            i.fi-x
                      - else
                        td = link_to worker.name, set_worker_task_path(@task, worker_id: worker.id), method: :post
                      td = "#{number_to_currency worker.price} / час"
                      td = worker.skills.map {|skill| skill.language.name }.join(', ')
                      td == worker.tasks.where(status: [:assigned, :working, :finished, :rejected]).map {|x| link_to x.id, edit_task_path(x) }.join(', ')
            - else
              p Нет подходящих работников


      - disabled = current_user.client_manager? ? '' : ' disabled '
      = form_for(@task, html: {'data-abide'=> true}) do |f|
        .row
          .small-12.columns
            h5
              | Клиент:&nbsp;
              = Client.find(client_id).name
              - if current_user.client_manager?
                | &nbsp;(
                = link_to 'изменить', params.merge(client_id: :new)
                | )&nbsp;
        = f.hidden_field :client_id, value: client_id
        - languages_array = Language.all.map { |language| [language.name, language.id] }

        .row
          .small-6.columns
            .field
              = f.label :from_lang do
                = t '.from_lang'
                = f.select :from_lang_id, languages_array, {}, disabled: !(current_user.client_manager? || current_user.admin?)
              small.error = t '.translation_languages_should_be_different'
          .small-6.columns
            .field
              = f.label :to_lang do
                = t '.to_lang'
                = f.select :to_lang_id, languages_array, {}, 'data-abide-validator' => :differentTo, 'data-different-to' => :task_from_lang_id, disabled: !(current_user.client_manager? || current_user.admin?)
              small.error = t '.translation_languages_should_be_different'
        .row
          .small-3.columns
            .field
              = f.label :deadline do
                = t '.deadline'
                = f.text_field :deadline, disabled: !(current_user.client_manager? || current_user.admin?), value: l(@task.deadline || Date.today + 5.days), class: 'datepicker'
              small.error = t '.not_valid_date'
          .small-3.columns
            - if current_user.client_manager? || current_user.admin? || current_user.profreader? || current_user.project_manager?
              .field
                = f.label :price do
                  = t '.price'
                  .row.collapse
                    .small-2.columns
                      span.prefix = t 'number.currency.format.unit'
                    .small-10.columns
                      = f.text_field :price, required: true, pattern: 'currency', disabled: !(current_user.client_manager? || current_user.admin?)
                  small.error = t '.not_valid_currency'
          div class="columns small-#{(current_user.client_manager? || current_user.admin? || current_user.profreader? || current_user.project_manager?) ? 3 : 6}"
            .field
              = f.label :quality do
                = t '.quality'
                = f.number_field :quality, required: true, pattern: 'mark10', disabled: !(current_user.client_manager? || current_user.admin?)
              small.error = t '.not_valid_quality'
          .small-3.columns
            .field
              = f.label :size do
                = t '.size'
                = f.number_field :size, required: true, pattern: 'integer', disabled: !(current_user.client_manager? || current_user.admin?)
              small.error = t '.not_valid_size'
        .row
          .small-12.columns
            .field
              = f.label :description do
                = t '.description'
                = f.text_area :description, rows: 5, disabled: !(current_user.client_manager? || current_user.admin?)
              small.error = t '.not_valid_date'

        - if current_user.admin? || current_user.client_manager?
          .row
            .small-9.columns
              .actions
                = f.submit t('.save'), class: 'button expand'
            .small-3.columns
              = link_to t('cancel'), :back, class: 'button expand'
      - unless @task.new_record?
        h3 Комментарии
        - @task.comments.each do |comment|
          .row
            - if comment.source == 'translator'
              .small-10.columns
                p.buble-translator
                  span.title = "#{comment.worker.name}:"
                  span.text = comment.text
            - if comment.source == 'client_manager'
              .small-10.columns.right
                p.buble-client-manager
                  span.title = "Менеджер по работе с клиентами:"
                  span.text = comment.text
            - if comment.source == 'profreader'
              .small-10.columns.right
                p.buble-profreader
                  span.title = "Профридер:"
                  span.text = comment.text

        - if current_user.translator?
          = form_for Comment.new do |f|
            = f.hidden_field :source, value: :translator
            = f.hidden_field :worker_id, value: current_user.worker.id
            = f.hidden_field :task_id, value: @task.id

            .search-row
              .row.collapse
                .small-10.columns
                  = f.text_field :text, required: true, class: 'prefix text-left', placeholder: 'Добавьте ваш комментарий'
                .small-2.columns
                  = f.submit 'Добавить', class: 'button postfix'

        - elsif current_user.profreader?
          = form_for Comment.new do |f|
            = f.hidden_field :source, value: :profreader
            = f.hidden_field :task_id, value: @task.id

            .search-row
              .row.collapse
                .small-10.columns
                  = f.text_field :text, required: true, class: 'prefix text-left', placeholder: 'Добавьте ваш комментарий'
                .small-2.columns
                  = f.submit 'Добавить', class: 'button postfix'

        - elsif current_user.client_manager?
          = form_for Comment.new do |f|
            = f.hidden_field :source, value: :client_manager
            = f.hidden_field :task_id, value: @task.id

            .search-row
              .row.collapse
                .small-10.columns
                  = f.text_field :text, required: true, class: 'prefix text-left', placeholder: 'Добавьте ваш комментарий'
                .small-2.columns
                  = f.submit 'Добавить', class: 'button postfix'

        h3 Файлы
        .row
          .small-6.columns#source
            label Исходные файлы
            .row
              - @task.documents.source.each do |document|
                .small-11.columns
                  .document-block
                    = image_tag document.format + '.png', width: 50
                    span
                      = link_to document.document.url, class: 'title' do
                        = document.name
                .small-1.columns
                  - if current_user.admin? || current_user.client_manager?
                    .document-action-button
                      = link_to document_path(document), method: :delete do
                        i.fi-x
            .row
              - if current_user.admin? || current_user.client_manager?
                .small-6.columns
                  = link_to 'Скачать архивом', documents_task_path(id: @task.id, kind: 'source'), class: 'button expand'
                .small-6.columns
                  = form_for Document.new do |f|
                    = f.hidden_field :task_id, value: @task.id
                    = f.hidden_field :kind, value: :source
                    label
                      = f.file_field :document , class: 'file_submiter hide'
                      span.button.expand Добавить
              - else
                .small-12.columns
                  = link_to 'Скачать архивом', documents_task_path(id: @task.id, kind: 'source'), class: 'button expand'

          .small-6.columns#result
            label Результаты
            .row
              - @task.documents.result.each do |document|
                .small-11.columns
                  .document-block
                    = image_tag document.format + '.png', width: 50
                    span
                      = link_to document.document.url, class: 'title' do
                        = document.name
                .small-1.columns
                  - if current_user.admin? || current_user.translator?
                    .document-action-button
                      = link_to document_path(document), method: :delete do
                        i.fi-x
            .row
              - if current_user.admin? || current_user.translator?
                .small-6.columns
                  = link_to 'Скачать архивом', documents_task_path(id: @task.id, kind: 'result'), class: 'button expand'
                .small-6.columns
                  = form_for Document.new do |f|
                    = f.hidden_field :task_id, value: @task.id
                    = f.hidden_field :kind, value: :result
                    label
                      = f.file_field :document , class: 'file_submiter hide'
                      span.button.expand Добавить
              - else
                .small-12.columns
                  = link_to 'Скачать архивом', documents_task_path(id: @task.id, kind: 'result'), class: 'button expand'


  coffee:
    do setupTasksForm

app/views/tasks/edit.html.slim
.row
  .small-12.columns
    h1 Заказ № #{@task.id}

== render 'form'

app/views/tasks/index.html.slim
.row
  .small-5.columns
    h1 = t '.list_all_tasks'
- if current_user.client_manager? || current_user.profreader? || current_user.admin? || current_user.project_manager?
  .row
    .small-12.columns
      .search-row
        = form_tag(tasks_path, method: :get) do
          .row.collapse style='margin-bottom: 0px'
            .small-1.columns
              = link_to t('.all_tasks'), params.except(:filter, :q), class: "button prefix#{' active' unless params[:filter] || params[:q]}"
            .small-2.columns
              - if params[:filter] && params[:filter][:new]
                = link_to 'Новые', params.except(:filter, :q).merge(filter: params[:filter].except(:new)), class: "button prefix active"
              - else
                = link_to 'Новые', params.except(:q).merge('filter[new]' => true), class: "button prefix"
            .small-2.columns
              - if params[:filter] && params[:filter][:assigned]
                = link_to 'Распределенные', params.except(:filter, :q).merge(filter: params[:filter].except(:assigned)), class: "button prefix active"
              - else
                = link_to 'Распределенные', params.except(:q).merge('filter[assigned]' => true), class: "button prefix"
            .small-2.columns
              - if params[:filter] && params[:filter][:working]
                = link_to 'В работе', params.except(:filter, :q).merge(filter: params[:filter].except(:working)), class: "button prefix active"
              - else
                = link_to 'В работе', params.except(:q).merge('filter[working]' => true), class: "button prefix"
            .small-3.columns
              - if params[:filter] && params[:filter][:finished]
                = link_to 'Завершенные', params.except(:filter, :q).merge(filter: params[:filter].except(:finished)), class: "button prefix active"
              - else
                = link_to 'Завершенные', params.except(:q).merge('filter[finished]' => true), class: "button prefix"
            .small-2.columns
              - if params[:filter] && params[:filter][:rejected]
                = link_to 'Отклоненные', params.except(:filter, :q).merge(filter: params[:filter].except(:rejected)), class: "button prefix active"
              - else
                = link_to 'Отклоненные', params.except(:q).merge('filter[rejected]' => true), class: "button prefix"
          .row.collapse
            .small-2.columns
              - if params[:filter] && params[:filter][:ready]
                = link_to 'Готовые', params.except(:filter, :q).merge(filter: params[:filter].except(:ready)), class: "button prefix active"
              - else
                = link_to 'Готовые', params.except(:q).merge('filter[ready]' => true), class: "button prefix"
            .small-2.columns
              - if params[:filter] && params[:filter][:canceled]
                = link_to 'Отмененные', params.except(:filter, :q).merge(filter: params[:filter].except(:canceled)), class: "button prefix active"
              - else
                = link_to 'Отмененные', params.except(:q).merge('filter[canceled]' => true), class: "button prefix"
            .small-2.columns
              - if params[:filter] && params[:filter][:closed]
                = link_to 'Закрытые', params.except(:filter, :q).merge(filter: params[:filter].except(:closed)), class: "button prefix active"
              - else
                = link_to 'Закрытые', params.except(:q).merge('filter[closed]' => true), class: "button prefix"
            .small-5.columns
              = text_field_tag :q, params[:q], placeholder: 'Поиск'
            .small-1.columns
              input type='submit' class="button postfix" value=t('search')

.row
  .small-12.columns
    - if (@special_tasks + @tasks).count > 0
      table
        tbody
          thead
            tr
              th = t '.id'
              th = t '.description'
              th = t '.from_lang'
              th = t '.to_lang'
              th = t '.deadline'
              - if current_user.client_manager? || current_user.admin? || current_user.profreader? || current_user.project_manager?
                th = t '.price'
              th = t '.quality'
              th = t '.size'
              th Исполнитель
              th = t '.status'
              th (colspan=2 if current_user.admin?)
        tbody
          - (@special_tasks + @tasks).each do |task|
            tr class=('current' if @special_tasks.include? task)
              td = task.id
              td = task.description
              td = task.from_lang.name
              td = task.to_lang.name
              td = l task.deadline
              - if current_user.client_manager? || current_user.admin? || current_user.profreader? || current_user.project_manager?
                td = number_to_currency task.price
              td = task.quality
              td = task.size
              td = task.worker.try(:name)
              td
                = t('status.' + task.status)
              td
                = link_to edit_task_path(task) do
                  i.fi-pencil
              - if current_user.admin?
                td
                  = link_to task, data: {:confirm => t('are_you_sure')}, :method => :delete do
                    i.fi-x
    - else
      - if params[:filter]
        p По вашему запросу ничего не найдено
      - elsif current_user.client_manager? || current_user.profreader? || current_user.admin? || current_user.project_manager?
        p = t '.add_new_tasks'
      - else
        p На данный момент вам не назначено ни одного заказа. Ожидайте уведомления по email.

- if current_user.admin? || current_user.client_manager?
  .row
    .small-12.columns
      = link_to t('.new'), new_task_path, class: 'button expand'

app/views/tasks/new.html.slim
.row
  .small-12.columns
    h1 = t '.new_task'

== render 'form'

app/views/tasks/show.html.slim
p#notice = notice

p
  strong To lang:
  = @task.to_lang
p
  strong From lang:
  = @task.from_lang
p
  strong Deadline:
  = @task.deadline
p
  strong Price:
  = @task.price
p
  strong Quality:
  = @task.quality
p
  strong Size:
  = @task.size
p
  strong Finished:
  = @task.finished

= link_to 'Edit', edit_task_path(@task)
'|
= link_to 'Back', tasks_path