config/routes.rb
Rails.application.routes.draw do


  devise_for :users

  authenticated :user do

    resources :comments
    resources :skills
    resources :workers
    resources :documents

    resources :clients

    resources :tasks do
      post :set_status, on: :member
      post :set_worker, on: :member
      get :documents, on: :member
    end

    resources :languages
    resources :access_rights, only: [:index, :update, :destroy]

    get '/match', to: 'home#match'
    post '/match/results', to: 'home#match_results'
  end

  root 'home#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :tasks
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
    if params[:q]
      @clients = Client.where("LOWER(name) LIKE :q or LOWER(phone) LIKE :q or LOWER(email) LIKE :q", q: "%#{params[:q].mb_chars.downcase}%")
    end
    if request.xhr?
      render 'append'
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        if params[:source] == 'new_task'
          format.html { redirect_to new_task_path(client_id: @client.id)}
        elsif params[:source] == 'task'
          format.html { redirect_to edit_task_path(client_id: @client.id, id: params[:task_id])}
        else
          format.html { redirect_to :clients}
        end
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to :clients, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :email, :phone)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.slim
.row
  .small-12.columns
    = form_for client, html: {'data-abide'=> true} do |f|
      input type='hidden' value=source name='source'
      - if source == :task
        input type='hidden' value=task_id name='task_id'
      - if client.errors.any?
        #error_explanation
          h2 = "#{pluralize(client.errors.count, "error")} prohibited this client from being saved:"
          ul
            - client.errors.full_messages.each do |message|
              li = message
      .row
        .small-12.columns
          .field
            = f.label :name do
              = t '.name'
              = f.text_field :name, required: true
            small.error Введите имя
      .row
        .small-6.columns
          .field
            = f.label :email do
              = t '.email'
              = f.text_field :email, required: true, pattern: :email
            small.error Неверный email
        .small-6.columns
          .field
            = f.label :phone do
              = t '.phone'
              = f.text_field :phone, required: true
            small.error Неверный телефон
      .row
        .small-9.columns
          .actions
            = f.submit t('.save'), class: 'button expand'
        .small-3.columns
          = link_to t('cancel'), :back, class: 'button expand'

app/views/clients/append.js.erb
$('#clients_list').html('<thead></thead><tbody></tbody>')

<% if @clients.any? %>
  $('#clients_list thead').html('<tr><th>Имя</th><th>Email</th><th>Телефон</th></tr>')
<% else %>
  $('#clients_list thead').html('')
<% end %>

<% text = '' %>
<% @clients.each do |client| %>
  <% if params[:task_id] %>
    <% text = "#{text}<tr><td>#{link_to client.name, edit_task_path(client_id: client.id, id: params[:task_id])}</td><td>#{client.email}</td><td>#{client.phone}</td><tr>" %>
  <% else %>
    <% text = "#{text}<tr><td>#{link_to client.name, new_task_path(client_id: client.id)}</td><td>#{client.email}</td><td>#{client.phone}</td><tr>" %>
  <% end %>
<% end %>

$('#clients_list tbody').html('<%== text %>')

app/views/clients/edit.html.slim
.row
  .small-12.columns

    h1 Редактировать клиента

    == render 'form', client: @client, source: nil

app/views/clients/index.html.slim
.row
  .small-5.columns

    h1 Список клиентов

  .small-7.columns.search-row
    = form_tag(clients_path, method: :get) do
      .row.collapse
        .small-4.columns
          = link_to 'Все', :clients, class: 'button prefix'
        .small-6.columns
          = text_field_tag :q, params[:q], placeholder: 'Поиск'
        .small-2.columns
          input type='submit' class="button postfix" value='Поиск'



.row
  .small-12.columns
    table
      thead
        tr
          th = t '.name'
          th = t '.email'
          th = t '.phone'
          th Всего заказов
          th Активных заказов
          th colspan=3

      tbody
        - @clients.each do |client|
          tr
            td = client.name
            td = client.email
            td = client.phone
            td = link_to tasks_path(client_id: client.id) do
              = client.tasks.count
            td
              = client.tasks.active.count
              | &nbsp;
              = link_to new_task_path(client_id: client.id) do
                i.fi-plus


            td = link_to edit_client_path(client) do
              i.fi-pencil

            td = link_to client, data: {:confirm => 'Are you sure?'}, :method => :delete do
              i.fi-x

    br

    = link_to t('.new_client'), new_client_path, class: 'button expand'

app/views/clients/new.html.slim
.row
  .small-12.columns

    h1 Добавить клиента

    == render 'form', client: @client, source: nil

app/views/clients/show.html.slim
p#notice = notice

p
  strong Name:
  = @client.name
p
  strong Email:
  = @client.email
p
  strong Phone:
  = @client.phone

= link_to 'Edit', edit_client_path(@client)
'|
= link_to 'Back', clients_path