config/routes.rb
Rails.application.routes.draw do


  devise_for :users

  authenticated :user do

    resources :comments
    resources :skills
    resources :workers
    resources :documents

    resources :clients

    resources :tasks do
      post :set_status, on: :member
      post :set_worker, on: :member
      get :documents, on: :member
    end

    resources :languages
    resources :access_rights, only: [:index, :update, :destroy]

    get '/match', to: 'home#match'
    post '/match/results', to: 'home#match_results'
  end

  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def match
    @locked = params[:locked] || {}
    @ignored_workers = params[:ignored_workers] || []
    @ignored_tasks = params[:ignored_tasks] || []

    @result = Matcher::perform Worker.free, Task.where(status: :new), @locked, @ignored_tasks, @ignored_workers
    @best_result = Matcher::perform Worker.free, Task.where(status: :new), {}, [], []
    @not_best = @locked.any? || @ignored_tasks.any? || @ignored_workers.any?
  end

  def match_results
    JSON.parse(params[:pairs]).each do |x|
      Task.find(x['task_id'].to_i).update! worker_id: Worker.find(x['worker_id'].to_i).id
    end
    redirect_to :root
  end

  private

  def match_params
    params.require :worker_ids
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def locked_without_pair task_id, worker_id
    Hash[
      @locked.select {|k, v| k.to_s != task_id.to_s && v.to_s != worker_id.to_s}
    ]
  end

  def with_fixed_pair task_id, worker_id
    params.merge(
      locked: locked_without_pair(task_id, worker_id).merge(task_id.to_s => worker_id),
      ignored_workers: (@ignored_workers - [worker_id.to_s]).sort.uniq,
      ignored_tasks: (@ignored_tasks - [task_id.to_s]).sort.uniq
    )
  end

  def without_fixed_pair task_id, worker_id
    params.merge(
      locked: locked_without_pair(task_id, worker_id)
    )
  end

  def without_worker id
    params.merge(
      ignored_workers: (@ignored_workers + [id.to_s]).sort.uniq,
      locked: locked_without_pair(nil, id)
    )
  end

  def with_worker id
    params.merge(
      ignored_workers: (@ignored_workers - [id.to_s]).sort.uniq
    )
  end

  def without_task id
    params.merge(
      ignored_tasks: (@ignored_tasks + [id.to_s]).sort.uniq,
      locked: locked_without_pair(id, nil)
    )
  end

  def with_task id
    params.merge(
      ignored_tasks: (@ignored_tasks - [id.to_s]).sort.uniq
    )
  end
end

app/views/home/_admin_panel.html.slim
.row
  .small-12.columns
    h1 = t '.welcome'
.row
  .small-4.columns
    = link_to t('.edit_langs'), languages_path, class: 'button expand'
  .small-2.columns
    = link_to t('.edit_workers'), workers_path, class: 'button expand'
  .small-2.columns
    = link_to t('.edit_tasks'), tasks_path, class: 'button expand'
  .small-4.columns
    = link_to t('.edit_access'), access_rights_path, class: 'button expand'

app/views/home/_client_manager_panel.html.slim
.row
  .small-12.columns
    h1 Admin-панель kayquote
.row
  .small-3.columns
    = link_to 'Заказы', tasks_path, class: 'button expand'
  .small-3.columns
    = link_to 'Клиенты', clients_path, class: 'button expand'
  .small-6.columns
    = link_to 'Добавить заказ', new_task_path, class: 'button expand'

app/views/home/_profreader_panel.html.slim
.row
  .small-12.columns
    h1 = t '.welcome'
.row
  .small-6.columns
    = link_to t('.edit_workers'), workers_path, class: 'button expand'
  .small-6.columns
    = link_to t('.edit_tasks'), tasks_path, class: 'button expand'

app/views/home/_project_manager_panel.html.slim
.row
  .small-12.columns
    h1 = t '.welcome'
.row
  .small-4.columns
    = link_to t('.edit_workers'), workers_path, class: 'button expand'
  .small-4.columns
    = link_to t('.edit_tasks'), tasks_path, class: 'button expand'
  .small-4.columns
    = link_to t('.match_tasks'), match_path, class: 'button expand'

app/views/home/_translator_panel.html.slim
- if params[:edit] || !current_user.worker
  .row
    .small-12.columns
      = form_for(current_user.worker || Worker.new(user_id: current_user.id), html: {'data-abide'=> true})do |f|
        .field
          = f.label :name do
            | Имя
            .search-row
              .row.collapse
                .small-10.columns
                    = f.text_field :name, required: true
                    small.error Укажите имя
                .small-2.columns
                  .field
                    = f.submit 'Изменить', class: 'button expand postfix'
- else
  .row
    .small-12.columns
      h3
        | Добрый день,
        = current_user.worker.name
        | (
        = link_to 'изменить', params.merge(edit: true)
        | )
  .row
    .small-12.columns
      = link_to 'Заказы', :tasks, class: 'button expand'

app/views/home/index.html.slim
.row
  .small-12.columns
    = render 'admin_panel' if current_user.admin?
    = render 'project_manager_panel' if current_user.project_manager?
    = render 'profreader_panel' if current_user.profreader?
    = render 'client_manager_panel' if current_user.client_manager?
    = render 'translator_panel' if current_user.translator?
    - if current_user.not_granted?
      .panel = t('.have_no_rights')

app/views/home/match.html.slim
.row
  .small-12.columns
    table
      thead
        tr
          th
          - if @not_best
            th Текущее распределение
            th Оптимальное распределение
          - else
            th
      tbody
        tr
          td = t '.matched'
          td = @result.matched
          - if @not_best
            td
              = @best_result.matched
              - if @best_result.matched - @result.matched != 0
                  | &nbsp;(
                  - if @best_result.matched - @result.matched > 0
                    span.green-text = "+#{@best_result.matched - @result.matched}"
                  - else
                    span.red-text = "#{@best_result.matched - @result.matched}"
                  | )
        tr
          td = t '.rejected'
          td = @result.rejected
          - if @not_best
            td
              = @best_result.rejected
              - if @best_result.rejected - @result.rejected != 0
                  | &nbsp;(
                  - if @best_result.rejected - @result.rejected > 0
                    span.red-text = "+#{@best_result.rejected - @result.rejected}"
                  - else
                    span.green-text = "#{@best_result.rejected - @result.rejected}"
                  | )
        tr
          td = t '.free_workers'
          td = @result.free_workers
          - if @not_best
            td
              = @best_result.free_workers
              - if @best_result.free_workers - @result.free_workers != 0
                  | &nbsp;(
                  - if @best_result.free_workers - @result.free_workers > 0
                    span.red-text = "+#{@best_result.free_workers - @result.free_workers}"
                  - else
                    span.green-text = "#{@best_result.free_workers - @result.free_workers}"
                  | )
        tr
          td = t '.recieved'
          td.green-text = "+#{number_to_currency @result.recieved}"
          - if @not_best
            td.green-text = "+#{number_to_currency @best_result.recieved}"
        tr
          td = t '.payed'
          td.red-text = "-#{number_to_currency @result.payed}"
          - if @not_best
            td.red-text = "-#{number_to_currency @best_result.payed}"
        tr
          td = t '.profit'
          td
            b = number_to_currency @result.recieved - @result.payed
          - if @not_best
            td
              b
                = "#{number_to_currency(@best_result.recieved - @best_result.payed)}"
                - if number_with_precision(@best_result.recieved - @best_result.payed - @result.recieved + @result.payed, precesion: 2).to_f != 0
                  | &nbsp;(
                  - if @best_result.recieved - @best_result.payed - @result.recieved + @result.payed > 0
                    span.green-text = "+#{number_to_currency(@best_result.recieved - @best_result.payed - @result.recieved + @result.payed)}"
                  - else
                    span.green-text = "#{number_to_currency(@best_result.recieved - @best_result.payed - @result.recieved + @result.payed)}"
                  | )
    hr
.row
  .small-12.columns
    table
      thead
        tr
          th
            | Переводчик (
            = link_to 'снять ограничения', params.merge(ignored_workers: nil)
            | )
          th
            | Номер заказа (
            = link_to 'снять ограничения', params.merge(ignored_tasks: nil)
            | )
          th Описание заказа
          th
            | Принудительные назначения (
            = link_to 'снять все', params.merge(locked: nil)
            | )
      tbody
        - @result.pairs.each do |pair|
          tr
            td
              - if @ignored_workers.include? pair.worker.id.to_s
                = link_to with_worker(pair.worker.id), title: 'Снять ограничение'
                  i.fi-lock
                | &nbsp;
                span.cross-text.red-text = pair.worker.name
              - else
                = link_to without_worker(pair.worker.id), title: 'Не распределять заказы на этого переводчика'
                  i.fi-x
                | &nbsp;
                = pair.worker.name
            td
              - if @ignored_tasks.include? pair.task.id.to_s
                = link_to with_task(pair.task.id), title: 'Снять ограничение'
                  i.fi-lock
                | &nbsp;
                span.cross-text.red-text = pair.task.id
              - else
                = link_to without_task(pair.task.id), title: 'Не распределять этот заказ'
                  i.fi-x
                | &nbsp;
                = pair.task.id
            td = link_to pair.task.description, edit_task_path(pair.task)
            td
              - if @locked.keys.include? pair.task.id.to_s
                = link_to without_fixed_pair(pair.task.id, pair.worker.id), title: "Убрать принудительное назначение"
                  i.fi-lock
        - if @result.pairs.empty?
          - if @ignored_workers.empty? && @ignored_tasks.empty?
            tr
              td colspan=4
                h4.text-center.red-text На данный момент нет заказов, которые можно распределить между свободными работниками.
          - else
            tr
              td colspan=4
                h4.text-center
                  | Невозможно распределить заказы при таких ограничениях (
                  = link_to 'снять все ограничения', params.merge(ignored_workers: nil, ignored_tasks: nil)
                  | )
        - else
          tr
            td colspan=4
              = form_tag match_results_path, method: :post
                = hidden_field_tag :pairs, @result.pairs.map {|x| {worker_id: x.worker.id, task_id: x.task.id} }.to_json
                input type='submit' value='Подтвердить назначение заказов' class='button expand'
        tr
          td colspan=4
            hr
        - (@result.workers.map {|x| x.worker} - @result.pairs.map {|x| x.worker}).each do |worker|
          tr
            td
              - if @ignored_workers.include? worker.id.to_s
                = link_to with_worker(worker.id.to_s), title: 'Снять ограничение'
                  i.fi-lock
                | &nbsp;
                span.cross-text.red-text = worker.name
              - else
                = link_to without_worker(worker.id.to_s), title: 'Не распределять заказы на этого переводчика'
                  i.fi-x
                | &nbsp;
                = worker.name
            td -
            td -
            td
        - (@result.workers.first.bad.map {|x| x.task} + @result.workers.first.good.map {|x| x.task} - @result.pairs.map {|x| x.task}).each do |task|
          tr
            td -
            td
              - if @ignored_tasks.include? task.id.to_s
                = link_to with_task(task.id), title: 'Снять ограничение'
                  i.fi-lock
                | &nbsp;
                span.cross-text.red-text = task.id
              - else
                = link_to without_task(task.id), title: 'Не распределять этот заказ'
                  i.fi-x
                | &nbsp;
                = task.id
            td = link_to task.description, edit_task_path(task)
            td

    hr
    h3 Для получения подробной информации о распределении, нажмите на строку с переводчиком в таблице ниже
    hr
.row
  .small-12.columns
    table
      thead
        tr
          th
          th = t 'workers.index.name'
          th = t 'workers.index.price'
          th = t 'workers.index.langs'
      tbody
        - @result.workers.each do |worker|
          tr.worker-row id="worker-#{worker.worker.id}"
            td.td-link
              - if @ignored_workers.include? worker.worker.id.to_s
                = link_to with_worker(worker.worker.id), title: 'Снять ограничение'
                  i.fi-lock
              - else
                = link_to without_worker(worker.worker.id), title: 'Не распределять заказы на этого переводчика'
                  i.fi-x
            td
              - if @ignored_workers.include? worker.worker.id.to_s
                span.cross-text.red-text = worker.worker.name
              - else
                = worker.worker.name
            td = "#{number_to_currency worker.worker.price}#{t 'workers.index.per_hour'}"
            td = worker.worker.skills.map {|skill| skill.language.name }.join(', ')
          - [:good, :bad].each do |type|
            - if worker.send(type).count > 0
              tr class="worker-#{worker.worker.id}" style='display:none'
                td class="#{type == :good ? 'green' : 'red'}-text" colspan=4 = t(".#{type}")
              tr class="worker-#{worker.worker.id}" style='display:none'
                td colspan=4
                  table
                    tbody
                      thead
                        tr
                          th = t 'tasks.index.id'
                          th = t 'tasks.index.description'
                          th = t 'tasks.index.from_lang'
                          th = t 'tasks.index.to_lang'
                          th = t 'tasks.index.deadline'
                          th = t 'tasks.index.price'
                          th = t 'tasks.index.quality'
                          th = t 'tasks.index.size'
                          - if type == :bad
                            th = t'.reject_reason'
                          - else
                            th = t'.profit'
                            th
                    tbody
                      - worker.send(type).each do |task|
                        tr class="#{'task-choosen' if task.choosen} #{'task-locked' if task.locked}"
                          td
                            - if @ignored_tasks.include? task.task.id.to_s
                              span.cross-text.red-text = task.task.id
                              | &nbsp;
                              = link_to with_task(task.task.id), title: 'Снять ограничение'
                                i.fi-lock
                            - else
                              = task.task.id
                              | &nbsp;
                              = link_to without_task(task.task.id), title: 'Не распределять этот заказ'
                                i.fi-x
                          td = task.task.description
                          td = task.task.from_lang.name
                          td = task.task.to_lang.name
                          td = l task.task.deadline
                          td = number_to_currency task.task.price
                          td = task.task.quality
                          td = task.task.size
                          - if type == :bad
                            td
                              i.red-text = t("match.problems.#{task.description}",
                                              skill: task.try(:skill),
                                              expense: number_to_currency(task.try(:expense) || 0),
                                              income: number_to_currency(task.try(:income) || 0))
                          - else
                            td
                              i.green-text = number_to_currency task.profit
                            td.text-center
                              - if task.locked
                                  = link_to without_fixed_pair(task.task.id, worker.worker.id), title: "Убрать принудительное назначение"
                                    i.fi-lock
                              - if !task.locked && @locked.keys.include?(task.task.id.to_s)
                                = link_to 'Переназначить', with_fixed_pair(task.task.id, worker.worker.id), title: "Принудительно назначить заказ № #{task.task.id} для #{worker.worker.name} - предыдущее принудительное назначение этого заказа изчезнет"
                              - if !task.locked && @locked.values.include?(worker.worker.id.to_s)
                                = link_to 'Переназначить', with_fixed_pair(task.task.id, worker.worker.id), title: "Принудительно назначить заказ № #{task.task.id} для #{worker.worker.name} - предыдущее принудительное назначение этого переводчика изчезнет"

                              - if !@locked.keys.include?(task.task.id.to_s) && !@locked.values.include?(worker.worker.id.to_s)
                                = link_to 'Закрепить', with_fixed_pair(task.task.id, worker.worker.id), title: "Принудительно назначить заказ № #{task.task.id} для #{worker.worker.name}"
br
br
br
br
br
br