config/routes.rb
Rails.application.routes.draw do


  devise_for :users

  authenticated :user do

    resources :comments
    resources :skills
    resources :workers
    resources :documents

    resources :clients

    resources :tasks do
      post :set_status, on: :member
      post :set_worker, on: :member
      get :documents, on: :member
    end

    resources :languages
    resources :access_rights, only: [:index, :update, :destroy]

    get '/match', to: 'home#match'
    post '/match/results', to: 'home#match_results'
  end

  root 'home#index'

end

app/models/worker.rb
class Worker < ActiveRecord::Base
  scope :sorted, -> {order :name}
  scope :free, -> {where(id: all.pluck(:id) - Task.where(status: [:assigned, :working, :finished, :rejected]).pluck(:worker_id))}
  has_many :skills
  has_many :tasks

  validates_presence_of :name
  validates_numericality_of :price, greater_than: 0

  belongs_to :user

  def time_spent_on task
    to_speed = skills.where(language_id: task.to_lang_id).take.try :speed
    from_speed = skills.where(language_id: task.from_lang_id).take.try :speed


    if (to_speed && from_speed)
      (task.size / [from_speed, to_speed].min).ceil
    else
      nil
    end
  end

  def costs task
    price * time_spent_on(task)
  end

  def accepts? task
    to_skill = skills.where(language_id: task.to_lang_id).take
    from_skill = skills.where(language_id: task.from_lang_id).take

    return Hashie::Mash.new({task: task, result: false, description: "not_skilled_in", skill: task.from_lang.name}) unless from_skill
    return Hashie::Mash.new({task: task, result: false, description: "not_skilled_in", skill: task.to_lang.name}) unless to_skill
    return Hashie::Mash.new({task: task, result: false, description: "not_skilled_enough", skill: task.from_lang.name}) if from_skill.quality < task.quality
    return Hashie::Mash.new({task: task, result: false, description: "not_skilled_enough", skill: task.to_lang.name}) if to_skill.quality < task.quality
    return Hashie::Mash.new({task: task, result: false, description: "deadline"}) if time_spent_on(task).business_hours.from_now >= task.deadline
    cost = costs task
    return Hashie::Mash.new({task: task, result: false, description: "economicaly_bad", income: task.price, expense: cost}) if cost > task.price
    Hashie::Mash.new({task: task, result: true, profit: task.price - cost})
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :control_access

  before_action :set_worker, only: [:show, :edit, :update, :destroy]
  before_action :set_workers, only: [:index]

  # GET /workers
  # GET /workers.json
  def index
    @workers = @workers.where("LOWER(name) LIKE ?", "%#{params[:q].mb_chars.downcase}%") if params[:q]
    @searching = !! params[:q]
    @workers = @workers.page params[:page]
  end

  # GET /workers/1
  # GET /workers/1.json
  def show
  end

  # GET /workers/new
  def new
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
    @skills = @worker.skills
    @skill = Skill.new

    @tasks = Task.where(status: :new)
    @tasks = @tasks.to_a.select {|x| @worker.accepts?(x).result }
    @tasks = @worker.tasks.where(status: :assigned) + Task.where(id: @tasks.map(&:id) - @worker.tasks.where(status: :assigned).map(&:id))
  end

  # POST /workers
  # POST /workers.json
  def create
    @worker = Worker.new(worker_params)

    respond_to do |format|
      if @worker.save
        format.html { redirect_to workers_url }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /workers/1
  # PATCH/PUT /workers/1.json
  def update
    respond_to do |format|
      if @worker.update(worker_params)
        if current_user.translator?
          format.html { redirect_to :root }
        else
          format.html { redirect_to workers_url }
        end
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /workers/1
  # DELETE /workers/1.json
  def destroy
    @worker.destroy
    respond_to do |format|
      format.html { redirect_to workers_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_worker
    @worker = Worker.find(params[:id])
  end

  def set_workers
    @workers = Worker.all.sorted
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def worker_params
    params.require(:worker).permit(:name, :price)
  end

  def control_access
    redirect_to root_path unless current_user.admin? ||
                                 current_user.profreader? ||
                                 current_user.project_manager? ||
                                 current_user.translator?
  end
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/workers/_form.html.slim
.row
  .small-12.columns

    = form_for(@worker, html: {'data-abide'=> true})do |f|
      .row
        .small-8.columns
          .field
            = f.label :name do
              = t '.name'
              = f.text_field :name, required: true, disabled: !current_user.profreader?
            small.error = t '.need_name'
        .small-4.columns
          .field
            = f.label :price do
              = t '.price'
              .row.collapse
                .small-3.columns
                  span.prefix = "#{t 'number.currency.format.unit'} / час"
                .small-9.columns
                  = f.text_field :price, required: true, pattern: 'currency', disabled: !current_user.profreader?
              small.error = t '.not_valid_currency'
      - if current_user.profreader?
        .row
          .small-9.columns
            .actions
              = f.submit t('.save'), class: 'button expand'
          .small-3.columns
              = link_to t('cancel'), :back, class: 'button expand'

app/views/workers/_lang_list.html.slim
.row
  .small-12.columns
    h2 = t '.worker_properties'

.row
  .small-12.columns
    table#skill-list-table
      thead
        tr
          th = t '.language'
          th = t '.quality'
          th = t '.speed'
          th
      tbody
        - @skills.each do |skill|
          tr
            = render 'skill_form', skill: skill
            td
              - if current_user.profreader?
                = link_to skill, data: {:confirm => t('are_you_sure')}, :method => :delete do
                  i.fi-x
        - if current_user.profreader?
          tr
            = render 'skill_form', skill: @skill

- if current_user.profreader?
  coffee:
    do setupSkillForms

app/views/workers/_skill_form.html.slim
- if skill.new_record?
  td.no-form data-skill-id="new" colspan=4
    a.button.expand = t '.add_skill'
- else
  td.no-form data-skill-id="#{skill.id}" = skill.language.try(:name)
  td.no-form data-skill-id="#{skill.id}" = skill.quality
  td.no-form data-skill-id="#{skill.id}" = skill.speed

- languages_array = Language.all.map { |language| [language.name, language.id] }

td.form.hide data-skill-id=(skill.id || 'new') colspan=(skill.new_record? ? 4 : 3)
  = form_for(skill, html: {'data-abide'=> true}) do |f|
    fieldset
      = f.hidden_field :worker_id, value: @worker.id
      .row
        .small-4.columns
          .field
            = f.label :language do
              = t '.language'
              = f.select :language_id, languages_array, {} ,
                         'data-abide-validator' => :uniqueThrough,
                         'data-unique-through' => '.language-selector',
                         class: 'language-selector', disabled: !current_user.profreader?
            small.error = t '.cant_dublicate_lang'
        .small-4.columns
          .field
            = f.label :quality do
              = t '.quality'
              = f.number_field :quality, required: true, pattern: 'mark10', disabled: !current_user.profreader?

            small.error = t '.not_valid_quality'
        .small-4.columns
          .field
            = f.label :speed do
              = t '.speed'
              = f.number_field :speed, required: true, pattern: 'integer', disabled: !current_user.profreader?
            small.error = t '.not_valid_speed'
      - if current_user.profreader?
        .row
          .small-12.columns
            .actions
              = f.submit t('save'), class: 'button expand'

app/views/workers/edit.html.slim
.row
  .small-12.columns
    h1 = t '.edit_worker'

== render 'form'

== render 'lang_list'

- if current_user.project_manager?
  .row
    .small-12.columns
      h1 Подходящие заказы
      - if @tasks.count > 0
        table
          tbody
            thead
              tr
                th = t 'tasks.index.id'
                th = t 'tasks.index.description'
                th = t 'tasks.index.from_lang'
                th = t 'tasks.index.to_lang'
                th = t 'tasks.index.deadline'
                th = t 'tasks.index.price'
                th = t 'tasks.index.quality'
                th = t 'tasks.index.size'
          tbody
            - @tasks.each do |task|
              tr class=('current' if task.worker_id == @worker.id)
                td
                  - if task.worker_id == @worker.id
                    = task.id
                    | &nbsp;
                    = link_to set_worker_task_path(task, worker_id: nil), method: :post
                      i.fi-x
                  - else
                    = link_to task.id, set_worker_task_path(task, worker_id: @worker.id), method: :post
                td = task.description
                td = task.from_lang.name
                td = task.to_lang.name
                td = l task.deadline
                td = number_to_currency task.price
                td = task.quality
                td = task.size
      - else
        p Нет подходящих заказов

app/views/workers/index.html.slim
.row
  .small-6.columns
    h1 = t '.list_all_workers'
  .small-6.columns
    .search-row
      = form_tag(workers_path, method: :get) do
        .row.collapse
          .small-10.columns
            = text_field_tag :q, params[:q], placeholder: t('.search')
          .small-2.columns
            input type='submit' class="button postfix" value=t('search')

.row
  .small-12.columns
    - if @workers.count > 0
      table
        tbody
          thead
            tr
              th = t '.name'
              th = t '.price'
              th = t '.langs'
              th Текущие заказы
              th
        tbody
          - @workers.each do |worker|
            tr class=('current' if @highlighted_worker_id == worker.id)
              td = worker.name
              td = "#{number_to_currency worker.price}#{t '.per_hour'}"
              td = worker.skills.map {|skill| skill.language.name }.join(', ')
              td == worker.tasks.where(status: [:assigned, :working, :finished, :rejected]).map {|x| link_to x.id, edit_task_path(x) }.join(', ')
              td = link_to edit_worker_path(worker) do
                i.fi-pencil
      = paginate @workers
    - else
      - if @searching
        p = t '.nothing_found'
      - else
        p = t '.add_new_workers'

/ .row
/   .small-12.columns
/     = link_to t('.new'), new_worker_path, class: 'button expand'

app/views/workers/new.html.slim
.row
  .small-12.columns
    h1 = t '.new_worker'

== render 'form'

app/views/workers/show.html.slim
p#notice = notice

p
  strong Name:
  = @worker.name
p
  strong Price:
  = @worker.price

= link_to 'Edit', edit_worker_path(@worker)
'|
= link_to 'Back', workers_path